package DatiTraffico;

public enum Evento {
	CALATOELEVATO,
	CALATOMEDIO,
	CALATOSCORREVOLE,
	CALATOASSENTE,
	AUMENTATOSCORREVOLE,
	AUMENTATOMEDIO,
	AUMENTATOELEVATO,
	AUMENTATOBLOCCATO,
	RIMASTOELEVATO,
	RIMASTOBLOCCATO
}
